### ISSUE TITLE
Buffer: expected lifetime parameter

### ISSUE THREAD

**Issue by seirl** [poljar/ripgrep-weechat#1]
I'm trying to install ripgrep-weechat on my debian stable install. I installed the following dependencies:

- cargo
- clang
- libclang-dev
- rustc

When I run `make` I get the following error:

```
cargo build --release
   Compiling weechat-ripgrep v0.1.0 (/home/seirl/contrib/ripgrep-weechat)
error[E0106]: missing lifetime specifier
 --> src/buffer.rs:7:13
  |
7 |     buffer: Buffer
  |             ^^^^^^ expected lifetime parameter

error: aborting due to previous error

For more information about this error, try `rustc --explain E0106`.
error: Could not compile `weechat-ripgrep`.

To learn more, run the command again with --verbose.
make: *** [Makefile:13: target/release/libripgrep.so] Error 101
```

Did I miss something?

**Comment by poljar** [comment]
The rust Weechat bindings are going through some changes and this hasn't been updated. I pinned it now to a version that builds. 

Note that this plugin is very much beta quality.

**Comment by seirl** [comment]
Thanks!

> Note that this plugin is very much beta quality.

Holy shit you weren't kidding. I gave it an unrecognized option and it crashed weechat :-O
